// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehapwpkprcoackowbydc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoYXB3cGtwcmNvYWNrb3dieWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2NjM4MDksImV4cCI6MjA0OTIzOTgwOX0.TzZAAOWFd_zDFpZnWXGFgDg7PtnfKF1FQp-C9K33oDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);